### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by maxzvyagin** [maxzvyagin/spaceray#1]
- [x] Update to be more flexible than argspace, just variables
- [ ] Figure out better way to count nums of GPUs without using torch
- [ ] CPU parallelization support
- [x] Make wandb integration better and entirely optional as well
- [ ] Update starting space coordination (picking up from middle of training) to account for splits instead of simple slice
